app = { name = "fenrir", version = "1.0.0" }

[server.ssh]
server_name = "fenrir-prod"
idle_close_seconds = 30

[server.http.tls]
enabled = true

[server.grpc.tls]
enabled = true

[security.http]
control_tokens = []

[security.identity]
environment = "prod"

[security.identity.external]
base_url = "https://127.0.0.1:8081"
jwks_url = "https://127.0.0.1:8081/jwks.json"

[security.identity.external.tls]
ca_cert_path = "env:FENRIR_IDENTITY_TLS_CA"
client_cert_path = "env:FENRIR_IDENTITY_TLS_CERT"
client_key_path = "env:FENRIR_IDENTITY_TLS_KEY"
accept_invalid_certs = false

[telemetry.tracing]
level = "error"

[modules]
bootstrap = ["fenrir-api"]

[modules.registry.tls]
ca_cert_path = "env:FENRIR_IDENTITY_TLS_CA"
client_cert_path = "env:FENRIR_IDENTITY_TLS_CERT"
client_key_path = "env:FENRIR_IDENTITY_TLS_KEY"
accept_invalid_certs = true
