use std::fs;
use std::io;
use std::net::SocketAddr;
use std::path::PathBuf;

use time::OffsetDateTime;

#[derive(Debug, Clone, Default)]
pub struct DevEnvArtifacts {
    pub per_service: Vec<(String, PathBuf)>,
    pub shared_env: Option<PathBuf>,
    pub shared_endpoint: Option<SocketAddr>,
    pub shared_expires_at: Option<OffsetDateTime>,
}

pub fn sanitize_service_id(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                ch
            } else {
                '-'
            }
        })
        .collect()
}

pub fn write_shell_env_file(path: &PathBuf, env_values: &[(String, String)]) -> io::Result<()> {
    let mut contents = String::from("# Autogenerated by `sync module`\n");
    for (key, value) in env_values {
        contents.push_str(&format!("export {}={}\n", key, quote_env_value(value)));
    }
    fs::write(path, contents)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(path)?.permissions();
        perms.set_mode(0o600);
        fs::set_permissions(path, perms)?;
    }
    Ok(())
}

pub fn write_plain_env_file(path: &PathBuf, env_values: &[(String, String)]) -> io::Result<()> {
    let mut contents = String::new();
    for (key, value) in env_values {
        contents.push_str(&format!("{}={}\n", key, quote_env_value(value)));
    }
    fs::write(path, contents)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(path)?.permissions();
        perms.set_mode(0o600);
        fs::set_permissions(path, perms)?;
    }
    Ok(())
}

fn quote_env_value(value: &str) -> String {
    let mut result = String::with_capacity(value.len() + 2);
    result.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            '$' => result.push_str("\\$"),
            '`' => result.push_str("\\`"),
            _ => result.push(ch),
        }
    }
    result.push('"');
    result
}
